### ISSUE TITLE
Model reasoning

### ISSUE THREAD

**Issue by qly22** [jafarinia/snuffy#2]
Can inference scripts be shared, and weights that can be deduced directly

**Comment by jafarinia** [comment]
I am uncertain about the exact meaning of “inference scripts.” However, the test function that evaluates the model on the test data for metrics such as WSI-level AUC is accessible in train.py (https://github.com/jafarinia/snuffy/blob/4b5b9187f8e4eb46cf7f36752759e11edbbba011/train.py#L453C5-L453C13).
Additionally, if you desire regions of interest, you can utilize roi.py.
Furthermore, the weights are located under “Training the Embedder” README.

**Comment by jafarinia** [comment]
Since there are no further comments, I believe the issue has been resolved. Therefore, I am closing the issue. Please do not hesitate to ask any additional questions if you have any.
